name: ArcadeManager MacOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            8.x
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22.x
      - name: Setup ElectronNET
        run: dotnet tool install --global ElectronNET.CLI
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test
      - name: Electronize ARM
        run: electronize build /target osx /electron-arch arm64
        working-directory: ./src/ArcadeManager
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ArcadeManager-macos
          path: ./src/ArcadeManager/bin/Desktop/*.*
      - name: Upload console binaries
        uses: actions/upload-artifact@v4
        with:
          name: ArcadeManager-macos-console
          path: ./src/ArcadeManager.Console/bin/Release/net8.0/*.*
