name: ArcadeManager MacOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test
      - name: Publish
        run: dotnet publish -p:PublishProfile=osx-arm64
        working-directory: ./src/ArcadeManager
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ArcadeManager-macos
          path: ./src/ArcadeManager/publish/Release/net10.0/osx-arm64/*.*
      - name: Upload console binaries
        uses: actions/upload-artifact@v4
        with:
          name: ArcadeManager-macos-console
          path: ./src/ArcadeManager.Console/bin/Release/net10.0/*.*
