name: ArcadeManager MacOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            8.x
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22.x
      - name: Setup ElectronNET
        run: dotnet tool install --global ElectronNET.CLI
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Electronize
        run: electronize build /target osx
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ArcadeManager-macos
          path: ./src/bin/Desktop/*.*
